name: Auto Approve PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Approve PR
        if: github.event_name == 'pull_request'
        uses: yiwang-fever/test@v1 # bugbot:ignore untrusted-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
